github_repo: 'xCss'
# For use with the "Edit on GitHub" button, this represents the path to the
# source markdown, from the root of the GitHub repository, with no leading
# slash.  It's set to 'source' here as that's the Hexo default, though it can
# vary based on repository configuration (some variations use the
# less-preferred `content` directory.
content_root: 'source'

css_bundle: meteor
nav_class: dark

favicon: /images/favicon.ico

logo:
  nav_mobile: /images/valine.png
  url: '//valine.js.org'
  title: 'A fast, simple & powerful comment system.'
  subtitle: 'Valine'


apis:
  baidu: 3a67769b7760c62aafb6fa58d51da74c 
  ga: UA-61934506-3       
  marketo: 999-999-9999
  segment: abcabcabcabc
  docsearch:
    apiKey: c4ef5def993e015b66f3ea438e2be874
    indexName: valinejs

# nav:
#   'language':
#     url: http://www.meteor.com/tutorials
#     partial: illustration-guide
#     target: _new
#     active: false
#   'Guide':
#     url: http://guide.meteor.com
#     partial: illustration-compass
#     active: false
#   'API Docs':
#     url: http://docs.meteor.com
#     partial: illustration-logs
#     active: false

ad:
  enable: true

sidebar:
  null:
    - index
    - quickstart
    - changelog
  Config:
    - configuration
    - avatar
    - notify
    - i18n
    - visitor
    - emoji
  Other:
    - jekyll
    - hexo
    - vuepress
    - gatsby
    - cdn
    - contact
    - faq

valine:
  enable: true
  appId: 3GiiCyXCrGbOIH3EelCfJ6yw-gzGzoHsz
  appKey: iuneD4hXPQImdHQSRE0aOcRF
  notify: true
  placeholder: Just Go Go.
  avatar: mp
  enableQQ: true
  cdn: //unpkg.com/valine/dist/Valine.min.js # /script/Valine.min.js # https://cdn.jsdelivr.net/npm/valine
  


social_links:
  github: 'https://github.com/xCss'
  twitter: '@xCss'

